### PR TITLE
Initial files

### PR DESCRIPTION
**Pull request by jdebacker**
This PR adds initial data files and scripts to create them.

### CODE REVIEW

**Comment by jdebacker** [comment]
This PR is almost ready. I'm working on a GH Action that automates this and updates the data files every 4 months.  But I'm still trying to figure out how to create a new tag and release with each update (so we can better archive updates).

**Comment by jdebacker** [comment]
This PR is ready for review, @SeaCelo and @rickecon

**Comment by marcelolafleur** [comment]
@jdebacker @rickecon  in `fetch_un_data.py`, the token is not formatted correctly. The standard format is: `Bearer xyz` (with the space between word Bearer and token itself). 

Suggested correction: in line `68`, add 
`un_token = "Bearer " + un_token`

With this fix the script runs fine and gets me all the data. 

It would be useful to give the user some feedback, maybe with the list of files downloaded.

**Comment by jdebacker** [comment]
@SeaCelo -- good suggestion.  I will make that change.

**Comment by jdebacker** [comment]
> It would be useful to give the user some feedback, maybe with the list of files downloaded.

Let me think about this.  I was assuming this repo would basically be just a repository of data and the script to get those data would run automatically via GH Actions (i.e., not necessarily intended for anyone's use beyond you, me, and Rick).

**Comment by jdebacker** [comment]
@SeaCelo -- I've added some progress reporting (e.g., "Downloading data for ZAF") and a printed statement that the downloads successfully finished.

**Comment by marcelolafleur** [comment]
@jdebacker Looks good to me. A very nice addition

**Comment by jdebacker** [comment]
Thank you for the review @SeaCelo.  This PR is ready to merge unless you see other items to address.

**Comment by marcelolafleur** [comment]
Merging

**Pull request merged**
